environment: prime

aws_default_profile:



cicd:
  github_oidc:
    aws_profile: arfin-admin
    aws_region: eu-west-1
    github_organization: "nadirarfi"
    repository_name: "blog.nadirarfi.com"
    branch_name: "main"
    role_name: "BlogNadirArfiGithubActionRole"
    stack_name: "blog-nadirarfi-github-actions-oidc-role"
    oidc_provider_ssm_param: "/nadirarfi/github/actions/oidc/provider/arn"
    policy_arns:
      - "arn:aws:iam::aws:policy/AdministratorAccess"
