environment: prod

domain:
  name: blog.nadirarfi.com
  hostedZoneName: nadirarfi.com

features:
  useCloudFront: true
  useCustomDomain: true

aws:
  certificateRegion: us-east-1
  deploymentRegion: eu-west-1
  account: null
  ssm:
    hostedZoneIdSsmParam: /arfin/aws/ssm/route53/dns/public/hostedzone/nadirarfi.com/id
    cloudFrontDistributionIdSsmParam: /arfin/aws/ssm/prod/blog/nadiarfi/com/cloudfront/distribution/id
    s3BucketNameSsmParam: /arfin/aws/ssm/prod/blog/nadiarfi/com/s3/bucket/name

tags:
  Environment: prod
  Project: blog.nadirarfi.com
  IaC: CDK
